version: '3'
services:
    nginx:
        image: nginx:1.15-alpine
        ports:
            - "8080:80"
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/www/isometric:/var/www/isometric
