version: '3'
services:
    nginx:
        image: nginx:1.15-alpine
        ports:
            - "8080:80"
        volumes:
            - ./appdata/nginx:/etc/nginx/conf.d
            - ./appdata/www/isometric:/var/www/isometric
    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        ports:
            - "8081:80"
        volumes:
            - /var/run/postgresql:/var/run/postgresql
            - ./appdata/model:/model
            - ./data:/data
